language: node_js
node_js:
   - "8"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo aptitude -y install ttf-mscorefonts-installer > /dev/null
  - sudo fc-cache
before_script:
  - npm run flow-typed
script:
  - npm run test
sudo: required
dist: trusty
addons:
  firefox: "52.0"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
